trigger:
- master

jobs:
- job: BuildDockerImage
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'myregistry'
      repository: 'my-iot-app'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: 'v1'
